// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"UserCode/vmControl.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/BrowsevmControls.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/EditVirtualMachine.lsml.js\"></script>");
